import sqlite3
from datetime import datetime, timezone

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import func, select
from sqlalchemy.orm import sessionmaker

from app.database import create_sqlite_engine, get_db, initialize_database
from app.main import create_app
from app.models import Action, Deployment, Incident, LogEvent, Metric, Service


@pytest.fixture
def test_app(tmp_path):
    db_engine = create_sqlite_engine(f"sqlite:///{tmp_path / 'api-tests.sqlite'}")
    factory = sessionmaker(bind=db_engine, autoflush=False, expire_on_commit=False)
    application = create_app(db_engine)

    def override_get_db():
        with factory() as db:
            yield db

    application.dependency_overrides[get_db] = override_get_db
    try:
        with TestClient(application) as client:
            yield client, factory
    finally:
        db_engine.dispose()


def test_health_and_paginated_collections_are_available_at_both_prefixes(test_app):
    client, _ = test_app
    for path in ("/health", "/api/health"):
        response = client.get(path)
        assert response.status_code == 200
        assert response.json() == {"status": "ok", "database": "connected"}

    services = client.get("/services?skip=1&limit=2")
    assert services.status_code == 200
    assert services.json()["total"] == 8
    assert len(services.json()["items"]) == 2
    assert services.json()["skip"] == 1

    incidents = client.get("/api/incidents?skip=1&limit=1")
    assert incidents.status_code == 200
    assert incidents.json()["total"] == 3
    assert len(incidents.json()["items"]) == 1
    assert incidents.json()["items"][0]["service_id"] > 0


def test_incident_create_validation_and_related_records(test_app):
    client, _ = test_app
    service_id = client.get("/services?limit=1").json()["items"][0]["id"]

    invalid = client.post("/incidents", json={
        "title": " ",
        "severity": "urgent",
        "service_id": service_id,
    })
    assert invalid.status_code == 422
    assert "errors" in invalid.json()

    created = client.post("/api/incidents", json={
        "title": "Scenario created in API test",
        "severity": "high",
        "service_id": service_id,
        "summary": "A synthetic test symptom with enough context.",
    })
    assert created.status_code == 201
    incident = created.json()
    incident_id = incident["id"]
    assert incident["service_id"] == service_id
    assert incident["summary"] == "A synthetic test symptom with enough context."
    assert incident["is_synthetic"] is True

    detail = client.get(f"/incidents/{incident_id}")
    assert detail.status_code == 200
    assert detail.json()["title"] == incident["title"]
    assert client.get(f"/incidents/{incident_id}/evidence").json()["total"] == 1
    recommendation = client.get(f"/incidents/{incident_id}/recommendation")
    assert recommendation.status_code == 200
    assert "No infrastructure action" in recommendation.json()["action"]
    assert client.get(f"/incidents/{incident_id}/metrics").status_code == 200
    assert client.get(f"/incidents/{incident_id}/postmortem").status_code == 404

    missing_service = client.post("/incidents", json={
        "title": "Unknown service scenario",
        "severity": "low",
        "service_id": 999999,
    })
    assert missing_service.status_code == 404


def test_simulated_approval_and_validation_never_change_metric_records(test_app):
    client, factory = test_app
    incident_id = client.get("/incidents?limit=1").json()["items"][0]["id"]
    with factory() as db:
        before_metrics = list(db.scalars(select(Metric.value).order_by(Metric.id)).all())
        before_services = list(db.scalars(select(Service.status).order_by(Service.id)).all())

    approved = client.post(
        f"/api/incidents/{incident_id}/remediation/approve",
        json={"approved_by": "Test operator"},
    )
    assert approved.status_code == 200
    assert approved.json()["state"] == "approved"
    assert "No production" in approved.json()["result"]

    validated = client.post(f"/api/remediations/{approved.json()['id']}/validate")
    assert validated.status_code == 200
    assert validated.json()["state"] == "validated"
    assert validated.json()["validation_passed"] is True
    assert "no production metrics" in validated.json()["result"].lower()

    incident = client.get(f"/incidents/{incident_id}").json()
    assert incident["status"] == "resolved"
    with factory() as db:
        after_metrics = list(db.scalars(select(Metric.value).order_by(Metric.id)).all())
        after_services = list(db.scalars(select(Service.status).order_by(Service.id)).all())
        assert db.scalar(select(func.count()).select_from(Action)) == 1
    assert after_metrics == before_metrics
    assert after_services == before_services

    report = client.post(f"/incidents/{incident_id}/postmortem/generate")
    assert report.status_code == 200
    assert "not generated by AI" in report.json()["summary"]
    assert client.get(f"/incidents/{incident_id}/postmortem").status_code == 200


def test_legacy_sqlite_data_is_archived_and_migrated_without_loss(tmp_path):
    db_path = tmp_path / "legacy.sqlite"
    connection = sqlite3.connect(db_path)
    now = datetime.now(timezone.utc).isoformat()
    connection.executescript(
        """
        CREATE TABLE services (
            id INTEGER PRIMARY KEY, name TEXT, owner TEXT, tier TEXT, status TEXT,
            latency_ms REAL, error_rate REAL, request_rate REAL,
            latency_history TEXT, error_history TEXT, is_synthetic BOOLEAN
        );
        CREATE TABLE incidents (
            id INTEGER PRIMARY KEY, title TEXT, severity TEXT, status TEXT,
            service TEXT, summary TEXT, source TEXT, is_synthetic BOOLEAN, created_at TEXT
        );
        CREATE TABLE evidence (
            id INTEGER PRIMARY KEY, incident_id INTEGER, kind TEXT, source TEXT,
            message TEXT, observed_at TEXT, confidence REAL
        );
        CREATE TABLE runbooks (
            id INTEGER PRIMARY KEY, title TEXT, service TEXT, content TEXT, tags TEXT
        );
        CREATE TABLE remediations (
            id INTEGER PRIMARY KEY, incident_id INTEGER, action TEXT, state TEXT,
            created_at TEXT, approved_at TEXT, validation_passed BOOLEAN, result TEXT
        );
        CREATE TABLE postmortems (
            id INTEGER PRIMARY KEY, incident_id INTEGER, title TEXT, summary TEXT,
            root_cause TEXT, impact TEXT, prevention TEXT, created_at TEXT, is_synthetic BOOLEAN
        );
        """
    )
    connection.execute(
        "INSERT INTO services VALUES (7, 'legacy-api', 'Platform', 'Tier 1', 'Degraded', 250, 1.5, 80, '[100,250]', '[0.2,1.5]', 1)"
    )
    connection.execute(
        "INSERT INTO incidents VALUES (11, 'Legacy scenario', 'high', 'investigating', 'legacy-api', 'Preserve this summary', 'synthetic scenario', 1, ?)",
        (now,),
    )
    connection.execute(
        "INSERT INTO evidence VALUES (13, 11, 'log', 'legacy api', 'Preserve this signal', ?, 0.88)",
        (now,),
    )
    connection.execute(
        "INSERT INTO runbooks VALUES (17, 'Legacy runbook', 'legacy-api', 'Keep this procedure', 'legacy,test')"
    )
    connection.execute(
        "INSERT INTO remediations VALUES (19, 11, 'Review only', 'validated', ?, ?, 1, 'Imported simulation')",
        (now, now),
    )
    connection.execute(
        "INSERT INTO postmortems VALUES (23, 11, 'Legacy review', 'Keep report', 'Recorded cause', 'No real impact', 'Review signals', ?, 1)",
        (now,),
    )
    connection.commit()
    connection.close()

    db_engine = create_sqlite_engine(f"sqlite:///{db_path}")
    try:
        initialize_database(db_engine)
        factory = sessionmaker(bind=db_engine, autoflush=False, expire_on_commit=False)
        with factory() as db:
            service = db.get(Service, 7)
            incident = db.get(Incident, 11)
            assert service is not None and service.name == "legacy-api"
            assert incident is not None and incident.title == "Legacy scenario"
            assert db.scalar(select(func.count()).select_from(Metric)) >= 4
            assert db.scalar(select(Action.status).where(Action.id == 19)) == "simulated_validated"

        with db_engine.connect() as connection:
            names = set(__import__("sqlalchemy").inspect(connection).get_table_names())
            assert "legacy_services" in names
            assert "legacy_incidents" in names
            assert "services" in names and "incidents" in names
    finally:
        db_engine.dispose()


def test_checkout_simulation_is_synthetic_reproducible_and_resettable(test_app):
    client, factory = test_app

    baseline = client.get("/api/simulation/metrics")
    assert baseline.status_code == 200
    assert baseline.json()["state"] == "healthy"
    assert baseline.json()["is_synthetic"] is True
    assert len(baseline.json()["services"]) == 4
    assert all(service["is_synthetic"] for service in baseline.json()["services"])
    assert client.get("/api/simulation/health").json()["overall_status"] == "healthy"
    baseline_by_name = {service["name"]: service for service in baseline.json()["services"]}
    assert baseline_by_name["Checkout Service"]["latency_ms"] < 150
    assert baseline_by_name["Checkout Service"]["error_rate_percent"] < 1
    assert baseline_by_name["Database Service"]["db_pool_size"] == 50
    assert baseline_by_name["Database Service"]["db_pool_utilization_percent"] < 50
    assert all(
        service["history"][-1]["timestamp"]
        and max(point["latency_ms"] for point in service["history"])
        - min(point["latency_ms"] for point in service["history"]) < 5
        for service in baseline.json()["services"]
    )

    first_run = client.post("/api/simulation/start")
    assert first_run.status_code == 200
    first = first_run.json()
    assert first["state"] == "incident"
    assert first["run_number"] == 1
    by_name = {service["name"]: service for service in first["services"]}
    assert by_name["Database Service"]["db_pool_size"] == 10
    assert by_name["Database Service"]["db_pool_utilization_percent"] == 100
    assert by_name["Checkout Service"]["latency_ms"] == 2100
    assert by_name["Checkout Service"]["error_rate_percent"] == 16
    assert by_name["API Gateway"]["request_volume_rps"] > 2 * 240

    health = client.get("/api/simulation/health").json()
    assert health["overall_status"] == "degraded"
    assert all(service["status"] == "Degraded" for service in health["services"])

    events = client.get("/api/simulation/events").json()
    assert events["is_synthetic"] is True
    assert any(event["kind"] == "deployment" for event in events["items"])
    assert any("DB_POOL_SIZE changed from 50 to 10" in event["detail"] for event in events["items"])
    assert any("timeout" in event["detail"].lower() for event in events["items"])
    assert all(event["timestamp"] and event["is_synthetic"] for event in events["items"])
    assert len(events["items"]) == 8
    event_times = [datetime.fromisoformat(event["timestamp"]) for event in events["items"]]
    assert event_times == sorted(event_times, reverse=True)

    second = client.post("/api/simulation/start").json()
    assert second["run_number"] == 2
    for first_service, second_service in zip(first["services"], second["services"]):
        assert first_service["name"] == second_service["name"]
        assert [
            {key: value for key, value in point.items() if key != "timestamp"}
            for point in first_service["history"]
        ] == [
            {key: value for key, value in point.items() if key != "timestamp"}
            for point in second_service["history"]
        ]
    second_events = client.get("/api/simulation/events").json()["items"]
    assert [
        (event["kind"], event["level"], event["service"], event["title"], event["detail"])
        for event in events["items"]
    ] == [
        (event["kind"], event["level"], event["service"], event["title"], event["detail"])
        for event in second_events
    ]

    with factory() as db:
        checkout_service = db.scalar(select(Service).where(Service.name == "Checkout Service"))
        assert checkout_service is not None
        stored_metrics = db.scalar(
            select(func.count()).select_from(Metric).where(Metric.service_id == checkout_service.id)
        )
        assert stored_metrics == 21
        database_service = db.scalar(select(Service).where(Service.name == "Database Service"))
        assert database_service is not None
        assert db.scalar(
            select(func.count()).select_from(Deployment).where(Deployment.service_id == database_service.id)
        ) == 1
        assert db.scalar(
            select(func.count()).select_from(LogEvent).where(LogEvent.service_id == database_service.id)
        ) == 2

    reset = client.post("/api/simulation/reset")
    assert reset.status_code == 200
    assert reset.json()["state"] == "healthy"
    assert reset.json()["run_number"] == 2
    assert client.get("/api/simulation/health").json()["overall_status"] == "healthy"
    restored = {service["name"]: service for service in reset.json()["services"]}
    assert restored["Database Service"]["db_pool_size"] == 50
    assert restored["Database Service"]["db_pool_utilization_percent"] < 50
    assert restored["Checkout Service"]["error_rate_percent"] < 1
    assert client.get("/api/simulation/events").json()["is_synthetic"] is True